### ISSUE TITLE
GotOptions.headers.referer concats url pathname with itself

### ISSUE THREAD

**Issue by roblav96** [TypeCtrl/cloudflare#37]
I'm trying to get [digbt.org](https://www.digbt.org) working with this and I noticed the challenge solution request's `gotOptions.headers.referer` pathname is duplicated.

```js
got('https://www.digbt.org/search/ubuntu/?u=y')
```

<img width="749" alt="Screen Shot 2019-09-18 at 8 38 04 AM" src="https://user-images.githubusercontent.com/1457327/65149254-c3638080-d9ef-11e9-93bf-9c482ed259a0.png">

I'm not sure if this has anything to do with not being able to bypass Cloudflare, it seems to work fine on every other site I've tried so far.

**Comment by scttcper** [comment]
that site is returning a captcha. The other good library cloudscraper has the same issue, but throws a more useful error

**Comment by scttcper** [comment]
Unfortunately, i think this is the best we can do when websites are configured this way.
